first
modezzz/hw pull request #1
Opened 2022-11-27 15:36 UTC by modezzz

2022-11-29 09:38 UTC, shorodilov requested changes
Треба зробити рефакторінг класу товарів та внести відповідні зміни до кошика.

2022-11-29 09:38 UTC, shorodilov commented on main.py
> +        self.quantity = quantity
Інформацію щодо кількості треба посунути до класу кошика.

2022-11-29 09:38 UTC, shorodilov commented on main.py
> +        print(f'Total cart price products is: {total}')
Метод `total_price_cart` повинен повертати число.

2022-11-29 09:38 UTC, shorodilov commented on main.py
> +        return self.price * self.quantity
Спробуй `10.59 * 0.7` - виправ відповідно, щоб було людське число.

2022-11-29 23:21 UTC, shorodilov requested changes
Потребує додаткового рефакторінгу.

2022-11-29 23:21 UTC, shorodilov commented on main.py
> -    def cost_calc(self):
Нащо ти прибрав цей метод? Поверни назад.
Я просив просто його прорефакторити, щоб позбутись біди з плаваючою точкою.
Просто додай округлення до 2-х знаків після коми.

2022-11-29 23:21 UTC, shorodilov commented on main.py
> +        self.quantity = quantity
А що мені робити, якщо я бажаю придбати 1.5 кг яблук і 4 пачки соку? Брати два кошика?
Треба зробити структур таким чином, щоб можна було розділити окремі товари та відповідну їм кількість.

2022-11-29 23:21 UTC, shorodilov commented on main.py
> +        print(f'Total cart price products is: {round(total, 1)}')
Я ж просив повертати з цього метода numeric. І не забувай про проблему з плаваючою точкою.

2022-11-30 07:03 UTC, modezzz commented on main.py
> -    def cost_calc(self):
Я передвинув кількість в корзину, тому яким чином цей метод повинен працювати?

2022-12-05 11:44 UTC, shorodilov requested changes
Потребує допрацювання

2022-12-05 11:44 UTC, shorodilov commented on main.py
> +class Product:
Де метод для розрахунку вартості?

2022-12-05 11:44 UTC, shorodilov commented on main.py
> +        print(f'Total cart price products is: {round(total, 1)}')
Про всяк випадок - функція/метод повертає те, що зазначено після ключового слова `return`

2022-12-05 20:44 UTC, shorodilov requested changes
Метод `ShoppingCart.total_price_cart` потребує невеличких виправлень.

2022-12-05 20:44 UTC, shorodilov commented on main.py
> +            print(f'{prod} where are total amount is {round(total, 2)}')
Повертай `total`, не треба нічого друкувати до терміналу.

2022-12-05 20:44 UTC, shorodilov commented on main.py
> +            print(f'{prod} where are total amount is {round(total, 2)}')
І не забувай про скруглення для чисел з плавоючою точкою

2022-12-06 10:29 UTC, closed without merging